#ifndef EVENT_DEFINES_H
#define	EVENT_DEFINES_H

#define EVENT_BYTE1  0
#define EVENT_BYTE2  1
#define EVENT_BYTE3  2

#define EVENT_BIT1 0
#define EVENT_BIT2 1
#define EVENT_BIT3 2
#define EVENT_BIT4 3
#define EVENT_BIT5 4
#define EVENT_BIT6 5
#define EVENT_BIT7 6
#define EVENT_BIT8 7

#define EVENT_createId(byteNo, bitNo)    (uint16_t)(((uint16_t)((byteNo)<<8U)) | (0x01U << bitNo))
#define EVENT_getIdByte(evt)  (uint8_t)((evt) >> 8U)
#define EVENT_getIdBit(evt)   (uint8_t)((evt) & 0xFFU)

enum EVENT_ID_e {
    EVENT_ID_0x0001 = EVENT_createId(EVENT_BYTE1, EVENT_BIT1),
    EVENT_ID_0x0002 = EVENT_createId(EVENT_BYTE1, EVENT_BIT2),
    EVENT_ID_0x0004 = EVENT_createId(EVENT_BYTE1, EVENT_BIT3),
    EVENT_ID_0x0008 = EVENT_createId(EVENT_BYTE1, EVENT_BIT4),
    EVENT_ID_0x0010 = EVENT_createId(EVENT_BYTE1, EVENT_BIT5),
    EVENT_ID_0x0020 = EVENT_createId(EVENT_BYTE1, EVENT_BIT6),
    EVENT_ID_0x0040 = EVENT_createId(EVENT_BYTE1, EVENT_BIT7),
    EVENT_ID_0x0080 = EVENT_createId(EVENT_BYTE1, EVENT_BIT8),

    EVENT_ID_0x0101 = EVENT_createId(EVENT_BYTE2, EVENT_BIT1),
    EVENT_ID_0x0102 = EVENT_createId(EVENT_BYTE2, EVENT_BIT2),
    EVENT_ID_0x0104 = EVENT_createId(EVENT_BYTE2, EVENT_BIT3),
    EVENT_ID_0x0108 = EVENT_createId(EVENT_BYTE2, EVENT_BIT4),
    EVENT_ID_0x0110 = EVENT_createId(EVENT_BYTE2, EVENT_BIT5),
    EVENT_ID_0x0120 = EVENT_createId(EVENT_BYTE2, EVENT_BIT6),
    EVENT_ID_0x0140 = EVENT_createId(EVENT_BYTE2, EVENT_BIT7),
    EVENT_ID_0x0180 = EVENT_createId(EVENT_BYTE2, EVENT_BIT8),

    EVENT_ID_0x0201 = EVENT_createId(EVENT_BYTE3, EVENT_BIT1),
    EVENT_ID_0x0202 = EVENT_createId(EVENT_BYTE3, EVENT_BIT2),
    EVENT_ID_0x0204 = EVENT_createId(EVENT_BYTE3, EVENT_BIT3),
    EVENT_ID_0x0208 = EVENT_createId(EVENT_BYTE3, EVENT_BIT4),
    EVENT_ID_0x0210 = EVENT_createId(EVENT_BYTE3, EVENT_BIT5),
    EVENT_ID_0x0220 = EVENT_createId(EVENT_BYTE3, EVENT_BIT6),
    EVENT_ID_0x0240 = EVENT_createId(EVENT_BYTE3, EVENT_BIT7),
    EVENT_ID_0x0280 = EVENT_createId(EVENT_BYTE3, EVENT_BIT8),

    EVENT_ID_LAST
};

typedef enum EVENT_ID_e EVENT_ID_t;

#define EVENT_BYTES_LEN 3U


#endif	/* EVENT_DEFINES_H */

